### ISSUE TITLE
Buffer not retrieved by getBuffer(...) method

### ISSUE THREAD

**Issue by magne4000** [magne4000/node-libquassel#4]
```
4 - Special structure : IrcChannel
/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:587
                        buffer.topic = data.topic;
                                     ^
TypeError: Cannot set property 'topic' of null
    at handleStruct (/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:587:38)
    at dispatch (/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:134:13)
    at Socket.<anonymous> (/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:108:13)
    at Socket.emit (events.js:107:17)
    at handleData (/root/quassel-webserver/node_modules/libquassel/node_modules/qtdatastream/lib/qtdatastream.js:145:26)
    at TLSSocket.<anonymous> (/root/quassel-webserver/node_modules/libquassel/node_modules/qtdatastream/lib/qtdatastream.js:114:13)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at TLSSocket.Readable.push (_stream_readable.js:125:10)
    at TCP.onread (net.js:514:20)
```

**Comment by magne4000** [comment]
```
Received result
[ 4,
  <Buffer 49 72 63 43 68 61 6e 6e 65 6c>,
  '2/#r/dota2',
  { topic: '/r/Dota2 - Rules: http://bit.ly/ZvFjZK - Bot: !s(treams) !a(ll) - Live matches: http://goo.gl/JQvb4y',
    password: '',
    name: '#r/dota2',
    encrypted: 0,
    UserModes:
     { xrm: '',
       xCanucck: '',
       wickedplayer494: '',
       wey: '',
       wbn: '',
       'war-': '',
       wahlinerino: '',
       vegbrasil: '',
       trevarr: '',
       tekun: '',
       sumero: '',
       'steven-_': '',
       smu: '',
       random51: '',
       potatoe: 'v',
       poerisija: '',
       ouchjars: '',
       onoki: '',
       ntt: '',
       meeb: '',
       'lyaf``': '',
       lundiz: '',
       luch: '',
       lickuid_: '',
       leefan: '',
       lapiz: '',
       kstigs: 'o',
       kimbo_: '',
       kiimsz: '',
       kgoossens_: '',
       kennae: '',
       kanibe_: '',
       kanibe: '',
       kKaltUu: '',
       infussle_: '',
       icetea: '',
       heyda: '',
       gamma: 'o',
       ffshow: '',
       fekz: '',
       famer: '',
       fAn: '',
       'esp|flabbert': '',
       eses: '',
       dyslexicat: '',
       dunga: '',
       drmobius: '',
       dopelcat: '',
       devster31: '',
       deathroll: '',
       daxim: '',
       dan23: '',
       d4nky: '',
       crlsgms: '',
       computerquip: '',
       cherubim: '',
       boneal: 'o',
       bob: '',
       beffy: '',
       antigone: '',
       'aiR^^^^^^^^^^': '',
       'abunai`': '',
       Zombiebaron: '',
       Zeyall: '',
       Wigor: '',
       Wank: '',
       W_: '',
       WALLEN: '',
       Vakz: '',
       UnoPolak: '',
       Trell: '',
       Titibo: '',
       ThreeFive: '',
       Thom: '',
       ThePot: '',
       Tharuler: '',
       Suju: '',
       Sudden: '',
       Srmpu: '',
       Squirrely: '',
       Spoondalf: '',
       Snowblind: '',
       Skully: '',
       Samo: 'o',
       S: 'o',
       Ruohis: '',
       Robin_: '',
       Ravana: '',
       RAX: '',
       Q: 'o',
       ProN00b: 'o',
       PrinceOfDawn: '',
       PhalThrax: '',
       PepsiCoke: '',
       Pappaduck: '',
       Palmar: '',
       Palazzo: '',
       OrangeW2: '',
       OrangeW: '',
       OliverJonas: '',
       Nekit1234007: '',
       Nanne: '',
       Nanaya: '',
       Mushy: '',
       Motig: '',
       Milkweed: '',
       MikuzA: '',
       Mesh: '',
       'Massir`': '',
       Massir: '',
       Mark__: '',
       Maisteri: '',
       'Mad`oFF': '',
       LokusT: '',
       Laiz: '',
       Kild: '',
       Keytar: '',
       Karson: '',
       KA6: 'o',
       JustAPoring_: '',
       Jonii: '',
       JohnSlade: '',
       Jademalo: '',
       Hyd3: '',
       HoMM: '',
       Greyjoy: 'o',
       Graft: '',
       Fazy: '',
       Enemjay: '',
       DrU: '',
       Dororo: '',
       DongDongerson: '',
       DoggyOfWar: '',
       DetaX: '',
       Demeisen: '',
       Dembe: '',
       DJCoconutmilk: '',
       DEADBEEF_: '',
       D: 'o',
       Czechton1: '',
       'BullHorn-': '',
       Blazzu: '',
       Bizzelicious: '',
       BillyZane: '',
       'Aurum`': '',
       Alternity: '',
       A: 'o' },
    ChanModes: { D: 'nNtCT', C: {}, B: {}, A: [Object] } } ]
/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:587
                        buffer.topic = data.topic;
                                     ^
TypeError: Cannot set property 'topic' of null
    at handleStruct (/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:587:38)
    at dispatch (/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:134:13)
    at Socket.<anonymous> (/root/quassel-webserver/node_modules/libquassel/lib/libquassel.js:108:13)
    at Socket.emit (events.js:107:17)
    at handleData (/root/quassel-webserver/node_modules/libquassel/node_modules/qtdatastream/lib/qtdatastream.js:145:26)
    at TLSSocket.<anonymous> (/root/quassel-webserver/node_modules/libquassel/node_modules/qtdatastream/lib/qtdatastream.js:114:13)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:162:16)
    at TLSSocket.Readable.push (_stream_readable.js:125:10)
    at TCP.onread (net.js:514:20)
```
